import style from './theme.module.scss';

export const theme = {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: style['placeholder'],
  paragraph: style['paragraph'],
  quote: style['quote'],
  heading: {
    h1: style['heading-h1'],
    h2: style['heading-h2'],
    h3: style['heading-h3'],
    h4: style['heading-h4'],
    h5: style['heading-h5'],
    h6: style['heading-h6'],
  },
  list: {
    nested: {
      listitem: style['nested-listitem'],
    },
    ol: style['list-ol'],
    ul: style['list-ul'],
    listitem: style['listItem'],
    listitemChecked: style['listItemChecked'],
    listitemUnchecked: style['listItemUnchecked'],
  },
  hashtag: style['hashtag'],
  image: style['image'],
  link: style['link'],
  text: {
    bold: style['textBold'],
    code: style['textCode'],
    italic: style['textItalic'],
    strikethrough: style['textStrikethrough'],
    subscript: style['textSubscript'],
    superscript: style['textSuperscript'],
    underline: style['textUnderline'],
    underlineStrikethrough: style['textUnderlineStrikethrough'],
  },
  code: style['code'],
  codeHighlight: {
    atrule: style['tokenAttr'],
    attr: style['tokenAttr'],
    boolean: style['tokenProperty'],
    builtin: style['tokenSelector'],
    cdata: style['tokenComment'],
    char: style['tokenSelector'],
    class: style['tokenFunction'],
    'class-name': style['tokenFunction'],
    comment: style['tokenComment'],
    constant: style['tokenProperty'],
    deleted: style['tokenProperty'],
    doctype: style['tokenComment'],
    entity: style['tokenOperator'],
    function: style['tokenFunction'],
    important: style['tokenVariable'],
    inserted: style['tokenSelector'],
    keyword: style['tokenAttr'],
    namespace: style['tokenVariable'],
    number: style['tokenProperty'],
    operator: style['tokenOperator'],
    prolog: style['tokenComment'],
    property: style['tokenProperty'],
    punctuation: style['tokenPunctuation'],
    regex: style['tokenVariable'],
    selector: style['tokenSelector'],
    string: style['tokenSelector'],
    symbol: style['tokenProperty'],
    tag: style['tokenProperty'],
    url: style['tokenOperator'],
    variable: style['tokenVariable'],
  },
};